language: node_js

node_js:
  - 8
  - 6

script:
  - npm run lint
  - npm run test
  - npm run build

notifications:
  email:
    on_failure: change

cache:
  npm: true
  directories:
    - node_modules
