plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  ra-core@*:
    peerDependencies:
      final-form-arrays: "*"
      react-is: "*"
      history: "*"
      jsonexport: "*"
  ra-ui-materialui@*:
    peerDependencies:
      history: "*"
      react-is: "*"
      jsonexport: "*"
  react-admin@*:
    peerDependencies:
      history: "*"
      jsonexport: "*"
      react-is: "*"
  react-admin-date-inputs@*:
    peerDependencies:
      react-dom: "*"
  ra-language-english@*:
    peerDependencies:
      connected-react-router: "*"
      final-form: "*"
      final-form-arrays: "*"
      history: "*"
      jsonexport: "*"
      react: "*"
      react-dom: "*"
      react-final-form: "*"
      react-is: "*"
      react-redux: "*"
      react-router: "*"
      react-router-dom: "*"
      redux: "*"
      redux-saga: "*"
  ra-i18n-polyglot@*:
    peerDependencies:
      connected-react-router: "*"
      final-form: "*"
      final-form-arrays: "*"
      history: "*"
      jsonexport: "*"
      react: "*"
      react-dom: "*"
      react-final-form: "*"
      react-is: "*"
      react-redux: "*"
      react-router: "*"
      react-router-dom: "*"
      redux: "*"
      redux-saga: "*"
  recharts@*:
    peerDependencies:
      prop-types: "*"
